name: Treecapitator
version: 1.0.1-SNAPSHOT
main: Sdeyy.treecapitator.Treecapitator
api-version: 1.19
authors: [ Sdeyy ]
description: Behead those pesky trees without the need to cut them down completely.
